version: '4'
services:
  postgres:
    image: postgres:14.13
    container_name: postgresDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express
    volumes:
      - ./data:/data/db
  rabbitmq:
    image: rabbitmq:3.12
    container_name: rabbitmqDev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./data:/data/rabbitmq